### ISSUE TITLE
Library of videos

### ISSUE THREAD

**Issue by btajfel** [btajfel/Gold-Team#45]

**Comment by makaeladalley** [comment]
Effort Estimation: 3 story points

**Comment by makaeladalley** [comment]
Acceptance Criteria:
- After videos are saved, they will be placed in the users library of videos
- These videos will be automatically saved in order of last saved at the bottom of the page, with most recently saved at the top of the page
- Option to name videos

**Comment by azarrabi** [comment]
Reporter's user story: Lois is a young and upcoming news reporter who wants to be the first one to cover an event. When she suddenly hears a train crash, she and her friend collect footage and then edit the video on the spot and are able to post it in under 30 minutes.

**Comment by azarrabi** [comment]
User Type: Amateurs
User Action: View all the videos taken in your group
User Goal: To have every video in your group ready to view

**Comment by btajfel** [comment]
Git repo links to implement feature:
Gold-Team/screens/LibraryScreen.js
Gold-Team/screens/LibraryProject.js
Gold-Team/screens/GalleryScreen.js
Gold-Team/camcrew/api/projects.py
