### ISSUE TITLE
Add friend by Contact

### ISSUE THREAD

**Issue by tjsande** [btajfel/Gold-Team#76]
Effort Estimation: search, 2 story points

Acceptance Criteria:
* users have access to their contacts
* users can add, share and record with anyone in their contacts

**Comment by azarrabi** [comment]
User Type: Every user
User Action: Add people in your contacts to start a recording session with them
User Goal: To quickly add people in your contacts and start recording with them faster

**Comment by btajfel** [comment]
Git repo links to implement feature:
Gold-Team/screens/ContactRender.js
Gold-Team/screens/ContactsScreen.js
Gold-Team/camcrew/api/contacts.py
