### ISSUE TITLE
Recording with friends icons

### ISSUE THREAD

**Issue by tjsande** [btajfel/Gold-Team#77]
Acceptance Criteria:
Icons are individually colored
Icons only appear when someone has accepted an invite to record
Icons disappear if connection is lost

**Comment by azarrabi** [comment]
User Type: Amateurs
User Action: See which friends you're recording with
User Goal: To know which friends you're recording with

**Comment by btajfel** [comment]
Git repo links to implement feature:
Gold-Team/screens/RecordScreen.js
